zf_project/fish_app/urls.py
from django.urls import path

from .views import MultipleModelView, RackDetail, SubstockDetail, StockDetail, FishlineDetail, Racks, Rooms, FishlinesList

urlpatterns = [
    path('', MultipleModelView.as_view()),
    path('rack/<int:pk>', RackDetail.as_view(), name='rack'),
    path('available_racks', Racks.as_view(), name='racks'),
    path('rooms', Rooms.as_view(), name='rooms'),
    path('substock/<int:pk>', SubstockDetail.as_view(), name='substock'),
    path('stock/<int:pk>', StockDetail.as_view(), name='stock'),
    path('fishline/<int:pk>', FishlineDetail.as_view(), name='fishline'),
    path('fishlines', FishlinesList.as_view(), name='fishlineslist'),

]

zf_project/zf_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('fish_app/', include('fish_app.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name="useraccounts/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="useraccounts/logout.html"), name="logout"),
    path('admin/', admin.site.urls),
]

zf_project/fish_app/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Fishline(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    room = models.CharField(max_length=15)

    def __str__(self):
        return self.room


class Rack(models.Model):
    rackname = models.CharField(max_length=20, unique=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    row_count = models.PositiveIntegerField(null=True)
    col_count = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.rackname

    def get_row_range(self):
        row_range = range(1, (self.row_count+1))
        return row_range

    def get_col_range(self):
        col_range = range(1, (self.col_count+1))
        return col_range


class Position(models.Model):

    rack = models.ForeignKey(Rack, on_delete=models.CASCADE)
    row = models.IntegerField(null=True)
    column = models.IntegerField(null=True)

    def __str__(self):
        return "%s %s %s / %s" % (self.rack.room, self.rack.rackname, self.row, self.column)


class Stock(models.Model):
    fishline = models.ForeignKey(Fishline, on_delete=models.CASCADE)
    d_o_b = models.DateField(max_length=12)

    def __str__(self):
        return "{}, {}".format(self.fishline, self.d_o_b)

class Substock(models.Model):
    substock_id = models.AutoField(primary_key=True)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    position = models.OneToOneField(Position, on_delete=models.CASCADE)
    count = models.PositiveIntegerField(null=True)

    def __str__(self):
        return "Sub of {}".format(self.stock.fishline)


# creates Poisitons objects for each slot in a rack automatically after rack object creation
# adds / deletes positions after edit of rack
@receiver(post_save, sender=Rack)
def create_positions(sender, instance, created, update_fields=[], **kwargs):
        row_range = range(1, (instance.row_count + 1))
        col_range = range(1, (instance.col_count + 1))
        for x in row_range:
            for y in col_range:
                found = Position.objects.filter(rack=instance, row=x, column=y)
                if not found:
                    Position.objects.create(rack=instance, row=x, column=y)
        # checks for redundant positions in case rows/columns in rack were edited and adds or deletes them
        for position in (Position.objects.all()):
            if position.row not in row_range:
                position.delete()
            if position.column not in col_range:
                position.delete()

zf_project/fish_app/views.py
from django.views.generic import TemplateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Room, Rack, Position, Substock, Stock, Fishline

class MultipleModelView(TemplateView):
    template_name = 'fish_app/index.html'

    def get_context_data(self, **kwargs):
        context = super(MultipleModelView, self).get_context_data(**kwargs)
        context['rooms'] = list(Room.objects.all())
        context['racks'] = list(Rack.objects.all())
        context['positions'] = list(Position.objects.all())
        return context

class RackDetail(LoginRequiredMixin, DetailView):
    template_name = 'fish_app/rack.html'

    model = Rack

    def get_context_data(self, **kwargs):
        context = super(RackDetail, self).get_context_data(**kwargs)

        return context

class SubstockDetail(DetailView):
    template_name = 'fish_app/substock.html'

    model = Substock

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class StockDetail(DetailView):
    template_name = 'fish_app/stock.html'

    model = Stock

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class FishlineDetail(DetailView):
    template_name = 'fish_app/fishline.html'

    model = Fishline

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class Racks(ListView):
    template_name = 'fish_app/available_racks.html'

    model = Rack

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class Rooms(ListView):
    template_name = 'fish_app/rooms.html'

    model = Room

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class FishlinesList(ListView):
    template_name = 'fish_app/fishlines.html'

    model = Fishline

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context





# def login(request):
#     pass
#
# def index(request):
#     return render(request, 'zebrafish/index.html')

zf_project/fish_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>ZebraFish application</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <div>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/fish_app">FishAPP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'rooms' %}"> Rooms <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'racks' %}"> Racks <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'fishlineslist' %}"> Fishlines<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        </ul>
        </div>
    </nav>
        </div>
    </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

zf_project/fish_app/templates/fish_app/available_racks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Available Racks{% endblock %}

{% block content %}

{% for rack in rack_list %}
    Rack: <a href="{% url 'rack' rack.id %}">{{rack}}</a> located in: {{rack.room}}</li>

    <table id={{rack.rackname}} class="table">
{% with ''|center:rack.row_count as range1 %}
    <thead><tr>
        {% with ''|center:rack.col_count as range2 %}
        <th scope="col">X</th>
{% for _ in range2 %}
        <th scope="col">col {{forloop.counter}}</th>
    {% endfor %}
        {% endwith %}
        </tr></thead>
    {% for _ in range1 %}
    <tr>
        <th scope="row">row {{forloop.counter}}</th>
        {% with ''|center:rack.col_count as range2 %}
        {% for _ in range2 %}
        <td id={{forloop.counter}}>
            empty
        </td>
        {% endfor %}
        {% endwith %}
    </tr>
{% endfor %}
        {% endwith %}
        </table>

{% for position in rack.position_set.all %}
    <script> ro = {{position.row}}
        co = {{position.column}}
        table = "{{rack.rackname}}"

    </script>
    {% if position.substock %}
        <script>
        sub = "{{position.substock.stock}}"
        pos= {{position.substock.substock_id}}
        var row = document.getElementById(table).rows[(ro)].cells;
        row[(co)].innerHTML=sub
        </script>

    {% else %}
        <script>
        var row = document.getElementById(table).rows[(ro)].cells;
        row[(co)].innerHTML="empty"
        </script>

{% endif %}
{% endfor %}

List of Substock in rack {{rack.rackname}}:</br>

<!--adds info about Substock into the table according to substock's postion-->
{% for position in rack.position_set.all %}
{% if position.substock %}
<ul>
    <li><a href="{% url 'substock' position.substock.substock_id %}">{{ position.substock.stock }} count: {{position.substock.count}}</a>
</li>
</ul>
{% endif %}

{% endfor %}

{% endfor %}

{% endblock %}


</body>
</html>

zf_project/fish_app/templates/fish_app/fishline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fishlines</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Fishlines{% endblock %}

{% block content %}
<h1>Detail page for fishline {{fishline}}</h1>
    Stock of fishline {{fishline.name}}:
    <ul>{% for stock in fishline.stock_set.all %}
        <li>
            Born: {{stock.d_o_b}}
        </li>
        <ul>
        Substock:
            {% for substock in stock.substock_set.all %}
                <li>ID: {{substock.substock_id}}</li>
                <li>Count: {{substock.count}}</li>
                <li>Position: {{substock.position}}</li>
                </br>
            {% endfor %}
        </ul>
        {% endfor %}
    </ul>
</ul>
{% endblock %}
</body>
</html>

zf_project/fish_app/templates/fish_app/fishlines.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fishlines</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Fishlines{% endblock %}

{% block content %}
<ul>
{% for fishline in fishline_list %}
    <li>Fishline: <a href="{% url 'fishline' fishline.id %}">{{fishline.name}}</a>, description: {{fishline.description}}</li>
    Stock of fishline {{fishline.name}}:
    <ul>{% for stock in fishline.stock_set.all %}

        <li>
            Born: {{stock.d_o_b}}
            <ul>
            Substock:
            {% for substock in stock.substock_set.all %}
                <li>ID: {{substock.substock_id}}</li>
                <li>Count: {{substock.count}}</li>
                <li>Position: {{substock.position}}</li>
                </br>
            {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
{% endfor %}
</ul>


{% endblock %}


</body>
</html>

zf_project/fish_app/templates/fish_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h1>FishApp</h1>
This application helps manage stocks of zebrafish use for genetic experiments. It gives overwiew of rooms, racks and available positions,
about stock of fish and details about their dob, position, numbers. Select from the tabs in the navbar above to see information on specified subject.
In the list of items click on highlighted links to see detail page of item. To add, remove or edit items or information go to the admin section,
use 'Admin' tab of the navigation.
</br>

<h2>Simple overview</h2>
Overview of available rooms and racks in them.
And of currently grown fish, its stock and substock.</br>

Available rooms:
{% for room in rooms %}
<li>{{ room }}</li>
{% endfor %}

Available racks:
{% for rack in racks %}
<a href="{% url 'rack' rack.id %}">{{ rack.rackname }}</a>
{% endfor %}

<table>
    {% for position in positions %}

    <tr>
        <td>Akvarium: {{position.substock}}</td>
        <td>{{position}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}
</body>
</html>

zf_project/fish_app/templates/fish_app/rack.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

Rack :{{ rack.rackname }} </br>
Located in room: {{rack.room}}

<!--creates table automatically based on number of rows and columns in rack-->

<table id={{rack.rackname}} class="table">
{% with ''|center:rack.row_count as range1 %}
    <thead><tr>
        {% with ''|center:rack.col_count as range2 %}
        <th scope="col">X</th>
{% for _ in range2 %}
        <th scope="col">col {{forloop.counter}}</th>
    {% endfor %}
        {% endwith %}
        </tr></thead>
    {% for _ in range1 %}
    <tr>
        <th scope="row">row {{forloop.counter}}</th>
        {% with ''|center:rack.col_count as range2 %}
        {% for _ in range2 %}
        <td id={{forloop.counter}}>
            empty
        </td>
        {% endfor %}
        {% endwith %}
    </tr>
{% endfor %}
{% endwith %}</br>
</table>
</br>

{% for position in rack.position_set.all %}
<script> ro = {{position.row}}
    co = {{position.column}}
    table = "{{rack.rackname}}"

</script>
{% if position.substock %}
<script>
sub = "{{position.substock.stock}}"
pos= {{position.substock.substock_id}}
var row = document.getElementById(table).rows[(ro)].cells;
row[(co)].innerHTML=sub
</script>

{% else %}
<script>
var row = document.getElementById(table).rows[(ro)].cells;
row[(co)].innerHTML="empty"
</script>

{% endif %}
{% endfor %}

List of Substock in rack {{rack.rackname}}:

<!--adds info about Substock into the table according to substock's postion-->
{% for position in rack.position_set.all %}
{% if position.substock %}
<ul>
    <li><a href="{% url 'substock' position.substock.substock_id %}">{{ position.substock.stock }} count: {{position.substock.count}}</a>
</li>
</ul>
{% endif %}
{% empty %}
    No substock in this rag
{% endfor %}
{% endblock %}




</body>
</html>

zf_project/fish_app/templates/fish_app/rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rooms</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Rooms{% endblock %}

{% block content %}
<ul>
{% for room in room_list %}
    <li>Room: {{room}}, racks in room: {% for rack in room.rack_set.all %} <a href="{% url 'rack' rack.id %}">{{rack}}</a>, {% endfor %}</li>
{% endfor %}
</ul>


{% endblock %}


</body>
</html>

zf_project/fish_app/templates/fish_app/stock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

{{stock}}

List of substock and where they are located:
{% for substock in stock.substock_set.all %}
<li>
{{substock}}  :  {{substock.position}}
</li>
{% endfor %}
{% endblock %}

</body>
</html>

zf_project/fish_app/templates/fish_app/substock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}


{% endblock %}
Substock position:</br>
Rack: {{substock.position.rack.room}}</br>
Rack: {{substock.position.rack}}</br>
Row: {{substock.position.row}}</br>
Column: {{substock.position.column}}</br>

{% block content %}

</body>
</html>

zf_project/fish_app/templates/useraccounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

</body>
</html>

zf_project/fish_app/templates/useraccounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>